# Generated by Django 4.1.4 on 2022-12-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0002_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_on_chest",
            field=models.BooleanField(default=False),
        ),
    ]
