# Generated by Django 4.1.4 on 2022-12-17 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("list", "0003_item_is_on_chest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="list.list"
            ),
        ),
        migrations.AlterField(
            model_name="list",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
